- name: Reboot Server
  become: true
  register: reboot
  ansible.builtin.reboot:
  listen: 'cmtops.docker_rootless : Reboot Server'

- name: Restart Rootless Docker on Reconfig
  become: true
  when: reboot is undefined or not reboot.changed
  changed_when: true
  ansible.builtin.command:
    cmd: machinectl shell {{ rootless_user }}@ /bin/bash -c 'systemctl --user restart docker'
  listen: 'cmtops.docker_rootless : Restart Rootless Docker on Reconfig'
